apiVersion: v1
kind: Pod
metadata:
  name: test-pod
  labels:
    name: myapp
spec:
  containers:
    - name: nginx # 容器的名称
      image: nginx # 指定容器的镜像
      imagePullPolicy: IfNotPresent # 镜像拉取策略，指定如果本地有就用本地的，如果没有就拉取远程的
      volumeMounts:
        - name: pvc-config
          mountPath: /usr/share/nginx/html
          subPath: html
  volumes:
    - name: pvc-config
      persistentVolumeClaim:
        claimName: lustre-pvc

