apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: lustre-pvc
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: lustre-sc
  resources:
    requests:
      storage: 10Gi
  volumeMode: Filesystem

