apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: lustre-csi-controller
  namespace: kube-system
spec:
  selector:
    matchLabels:
      app: lustre-csi-controller
  serviceName: "lustre-csi-controller"
  replicas: 1
  template:
    metadata:
      labels:
        app: lustre-csi-controller
    spec:
      serviceAccountName: lustre-csi-controller-sa
      containers:
        - name: lustre-csi-plugin
          image: lustre-csi-driver:v1.0.0
          args:
            - "--endpoint=unix:///csi/csi.sock"
            - "--drivername=lustre.csi.k8s.io"
          volumeMounts:
            - name: socket-dir
              mountPath: /csi
      volumes:
        - name: socket-dir
          hostPath:
            path: /var/lib/kubelet/plugins/lustre.csi.k8s.io/
            type: DirectoryOrCreate
