apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: lustre-csi-node
  labels:
    app: lustre-csi
spec:
  selector:
    matchLabels:
      app: lustre-csi
  template:
    metadata:
      labels:
        app: lustre-csi
    spec:
      serviceAccountName: csi-node-sa
      containers:
        - name: liveness-probe
          image: registry.k8s.io/sig-storage/livenessprobe:v2.12.0
          args:
            - --csi-address=/csi/csi.sock
            - --probe-timeout=3s
            - --health-port=29653
            - --v=2
          volumeMounts:
            - name: socket-dir
              mountPath: /csi
          resources:
            limits:
              memory: 100Mi
            requests:
              cpu: 10m
              memory: 20Mi
        - name: csi-node-driver-registrar
          image: k8s.gcr.io/sig-storage/csi-node-driver-registrar:v2.5.0
          args:
            - "--v=5"
            - "--csi-address=$(CSI_ENDPOINT)"
            - "--kubelet-registration-path=/var/lib/kubelet/plugins/lustre.csi.k8s.io/csi.sock"
          env:
            - name: CSI_ENDPOINT
              value: unix:///csi/csi.sock
            - name: KUBE_NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
          volumeMounts:
            - name: plugin-dir
              mountPath: /csi
            - name: kubelet-dir
              mountPath: /var/lib/kubelet
              mountPropagation: Bidirectional
        - name: lustre-csi-driver
          image: lustre-csi-driver:v1.0.0
          args:
            - "--endpoint=$(CSI_ENDPOINT)"
            - "--nodeid=$(KUBE_NODE_NAME)"
          env:
            - name: CSI_ENDPOINT
              value: unix:///csi/csi.sock
            - name: KUBE_NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
          volumeMounts:
            - name: plugin-dir
              mountPath: /csi
            - name: kubelet-dir
              mountPath: /var/lib/kubelet
              mountPropagation: Bidirectional
          livenessProbe:
            exec:
              command:
                - /bin/sh
                - -c
                - "cat /tmp/lustre-csi-driver-healthz || exit 1"
            initialDelaySeconds: 10
            periodSeconds: 30
      volumes:
        - name: plugin-dir
          hostPath:
            path: /var/lib/kubelet/plugins/lustre.csi.k8s.io/
            type: DirectoryOrCreate
        - name: kubelet-dir
          hostPath:
            path: /var/lib/kubelet/
